### ISSUE TITLE
Doc

### ISSUE THREAD

**Issue by orlin369** [OpenMOBot/3DModels#4]
1 ✖️ 3DModels/design_stl/chassis/chassis.STL
4 ✖️ 3DModels/design_stl/chassis/motor_mount.STL
2 ✖️ 3DModels/design_stl/encoder_wheels/encoder_wheel_v4_20.STL
2 ✖️ 3DModels/design_stl/sensor_holder/mounting_part.STL
1 ✖️ 3DModels/design_stl/sensor_holder/sensor_holder.STL
2 ✖️ 3DModels/design_stl/sensor_holder/spacer.STL
4 ✖️ 3DModels/design_stl/sensor_holder/sturt.STL 

To be as links to the target file.

**Comment by majvazov** [comment]
Done
